### ISSUE TITLE
Отчет

### ISSUE THREAD

**Issue by mackoel** [Lexa496/python_bioinf#1]
Алексей, Issue надо было Вам создать. Есть замечания к отчету:
- нехватает подписей рисунков с номерами, чтобы ссылаться,
- изменение шага по отрезку предполагает координату t или х по оси абсцисс, не номер,
- следующий рисунок совсем непонятен, как размер от числа шагов,
- дальше то же,
- на последнем все сливается, можно меньше точностей проверять, но надо написать где какая компонента

**Comment by Lexa496** [comment]
Я исправил. Посмотрите, пожалуйста

**Comment by mackoel** [comment]
Зачел, хотя графики решений почему-то имеют разные шкалы по оси абсцисс не везде от начала до конца заданного интервала.
